### ISSUE TITLE
Wayland version.

### ISSUE THREAD

**Issue by lidgnulinux** [lauroro/hyprland-dotfiles#1]
Hello, it's a bit out of topic, which wayland version you are using ?
I heard that if we want to use workspace feature from waybar, we need to compile wayland which has workspace support. Thanks.

**Comment by lauroro** [comment]
It's not wayland related. It's waybar related. I remember that in the hyprland wiki the issue is well documented.
If you are on Arch Linux just remove waybar and run this:
`yay -S waybar-hyprland-git`

It's an already built waybar instance from AUR with the experimental stuff turned on. Then you can use my config as it is or you can start from there, as I'm using the correct workspaces plugin.
I wan't to mention that I don't know if all this has been fixed yet, I am not currently using hyprland, so I really don't know if all of this is still required. Check hyprland repo and maybe try with the default waybar package first. Feel free to let me know.

**Comment by lidgnulinux** [comment]
Oh, I see, thanks. I'll check it later.
